### ISSUE TITLE
[sls deploy error] Serverless plugin "serverless-offline" not found. 

### ISSUE THREAD

**Issue by harshes53** [adnanrahic/a-crash-course-on-serverless-apis-with-express-and-mongodb#1]
Hey @adnanrahic,

Great tutorial for newbies like me. Simple and yet a strong foundation CRUD app.

Although, I stumbled upon Serverless Error while deploying. 
```
  Serverless Error ---------------------------------------

  Serverless plugin "serverless-offline" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
```
I think it is because of `serverless-offline` plugin declared in `serverless.yml`. The packaging script is tryin to bundle `serverless-offline`. Since, as you suggested to delete `node_modules` and install with production flag.

What are the workarounds to develop/test offline and deploy seamlessly without changing `serverless.yml`, `secrets.json`(for changing NODE_ENV) and install/uninstall npm packages?

Thanks! 👍

**Comment by harshes53** [comment]
Found this information on [serverless.com](https://serverless.com/framework/docs/providers/aws/guide/packaging#development-dependencies)

Is it sufficient to not to re-install all the packages with `--production` flag?

**Comment by adnanrahic** [comment]
Yes! That's the option I'd go for. Feel free to add it and create a pull request. :ok_hand:
